/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.magata.fusion

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 *
 */
class FusionFinishPlugin implements Plugin<Project> {
    void apply(Project project) {
        // Fusion配置对象
        def fusion = project.extensions.Fusion
        fusion.handleConfig(project);
    }
}
