/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.magata.fusion

import org.gradle.api.Project
import org.gradle.api.Plugin
import com.magata.fusion.extensions.*

/**
 *
 */
class FusionPlugin implements Plugin<Project> {
    void apply(Project project) {
        // 创建Fusion配置扩展
        project.extensions.create("Fusion", FusionExtension.class)
    }
}
