/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.magata.fusion

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 *
 */
class FusionFinishPlugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
        // 依赖对象
        def dependencies = project.dependencies

        // Fusion配置对象
        def fusion = project.extensions.Fusion
        // manifestPlaceholders的keysMap 根据配置进行添加
        def keysMap = [:]
        // 配置了腾讯opensdk
        def data = fusion.getTencent()
        if (data.getEnabled().getOrNull() == true) {
            data.handleConfig(project)
        }

        // 配置了微信sdk
        data = fusion.getWeChat()
        if (data.getEnabled().getOrNull() == true) {
            data.handleConfig(project)
        }

        // 配置了隐私政策sdk
        data = fusion.getPrivacy()
        if (data.getEnabled().getOrNull() == true) {
            data.handleConfig(project)
        }

        // 设置 manifestPlaceholders
//        project.extensions.android.buildTypes.debug.manifestPlaceholders = keysMap
//        project.extensions.android.buildTypes.release.manifestPlaceholders = keysMap
//        project.extensions.android.defaultConfig.manifestPlaceholders = keysMap
    }
}
