/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.magata.fusion

import org.gradle.api.Project
import org.gradle.api.Plugin
import com.magata.fusion.extensions.*

/**
 *
 */
class FusionPlugin implements Plugin<Project> {
    void apply(Project project) {
        // 创建Fusion配置扩展
        project.extensions.create("Fusion", FusionExtension.class)
//        def fusionTask = project.tasks.register("fusion") {
//            //设置任务组
//            setGroup("magata gradle plugins")
//            // Fusion配置根对象
//            def fusion = project.extensions.Fusion
//            // manifestPlaceholders的keysMap 根据配置进行添加
//            def keysMap = [:]
//            // 依赖对象
//            def implementationConfig = project.configurations.getByName("implementation")
////            implementationConfig.setCanBeResolved(true)
//            // 配置了腾讯opensdk
//            def data = fusion.getTencent()
//            if (data.getEnabled().getOrNull() == 1) {
//                keysMap.tencentAppId = data.getAppId().get()
////                project.configurations.all { configuration ->
////                    def name = configuration.name
////                    System.out.println("this configuration is ${name}")
////                    if (name != "implementation") {
////                        return
////                    }
////                    //为Project加入Gson依赖
////                    configuration.dependencies.add(project.dependencies.create("com.magata.toolkits:opensdk:1.0.0"))
////                }
//            }
//
//            // 配置了微信sdk
//            data = fusion.getWeChat()
//            if (data.getEnabled().getOrNull() == 1) {
//                keysMap.weChatAppId = data.getAppId().get()
////                implementationConfig.add(dependencies.create("com.magata.toolkits:wechat:1.0.0"))
////                implementationConfig.add(dependencies.create("com.magata.toolkits:eventlisteners:1.0.0"))
////                implementationConfig.add(dependencies.create("com.magata.toolkits:fileprovider:1.0.0"))
////                implementationConfig.add(dependencies.create("com.magata.toolkits:utility:1.0.0"))
//            }
//
//            // 设置 manifestPlaceholders
//            project.extensions.android.buildTypes.debug.manifestPlaceholders = keysMap
//            project.extensions.android.buildTypes.release.manifestPlaceholders = keysMap
//            project.extensions.android.defaultConfig.manifestPlaceholders = keysMap
//        }

        // 设置fusion任务执行节点
//        project.tasks.preBuild.mustRunAfter fusionTask
//        project.tasks.preBuild.dependsOn fusionTask
    }
}
